language: julia
os:
  # - linux
  - osx
julia:
  #- 1.0
  #- 1.1
  #- 1.2
  #- 1.3
  #- 1.4
   - nightly
notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
