name = "DatagenCopulaBased"
uuid = "b9879e35-cdd4-53a9-a12a-bc41659e9769"
authors = ["Krzysztof Domino <kdomino@iitis.pl>", "Adam Glos <aglos@iitis.pl>"]
version = "1.3.2"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Combinatorics = "1"
CompilerSupportLibraries_jll = "0.3"
Distributions = "0.22, 0.23, 0.24"
HCubature = "1"
HypothesisTests = "0.9, 0.10"
QuadGK = "2"
Roots = "1"
SpecialFunctions = "0.10, 0.11, 1.2"
StatsBase = "0.32, 0.33"
julia = "1.4, 1.5"

[extras]
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PyCall", "Cubature", "StableRNGs"]
